// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtkEL3wxy29hBJfO9T5JVp5IVrntpEog',
    appId: '1:510022071223:web:d37797e248642dd71e2e32',
    messagingSenderId: '510022071223',
    projectId: 'bus-tracker-1d401',
    authDomain: 'bus-tracker-1d401.firebaseapp.com',
    storageBucket: 'bus-tracker-1d401.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HSERJ9FXwYNy7WKQImcAH2F7o-_-TW0',
    appId: '1:510022071223:android:e9a474b2c55f42581e2e32',
    messagingSenderId: '510022071223',
    projectId: 'bus-tracker-1d401',
    storageBucket: 'bus-tracker-1d401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgOC4DE9JTY7MExaTl2odkYi4sNSZFL7g',
    appId: '1:510022071223:ios:ff812b8f6b9a571d1e2e32',
    messagingSenderId: '510022071223',
    projectId: 'bus-tracker-1d401',
    storageBucket: 'bus-tracker-1d401.appspot.com',
    iosBundleId: 'com.example.busTrackerAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgOC4DE9JTY7MExaTl2odkYi4sNSZFL7g',
    appId: '1:510022071223:ios:ff812b8f6b9a571d1e2e32',
    messagingSenderId: '510022071223',
    projectId: 'bus-tracker-1d401',
    storageBucket: 'bus-tracker-1d401.appspot.com',
    iosBundleId: 'com.example.busTrackerAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrtkEL3wxy29hBJfO9T5JVp5IVrntpEog',
    appId: '1:510022071223:web:1d6ad1ea423847101e2e32',
    messagingSenderId: '510022071223',
    projectId: 'bus-tracker-1d401',
    authDomain: 'bus-tracker-1d401.firebaseapp.com',
    storageBucket: 'bus-tracker-1d401.appspot.com',
  );
}
